[package]
name = "pallet-asset-manager"
authors = ["PureStake"]
edition = "2021"
version = "0.1.0"

[dependencies]
log = { version = "0.4.21", default-features = false }
serde = { version = "1.0.197", default-features = false, optional = true }

# Moonbeam
xcm-primitives = { path = "../../primitives/xcm", default-features = false }

# Substrate
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
parity-scale-codec = { version = "3.6.5", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.10.0", default-features = false, features = [ "derive" ] }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }

# Polkadot
xcm = { package = "staging-xcm", git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }

# Benchmarks
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false, optional = true }

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", features = [ "insecure_zero_ed", "std" ] }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", features = [ "std" ] }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"frame-system/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-primitives/std",
	"xcm/std",
]

runtime-benchmarks = [ "frame-benchmarking", "xcm-primitives/runtime-benchmarks" ]
try-runtime = [ "frame-support/try-runtime" ]
